language_messages = {
    'uz_en': 'Siz "uz ➡️ en" tilini tanladingiz\nKerakli matnni kiriting',
    'en_uz': 'You chose "en ➡️ uz" language\nEnter the text you want to translate',
    'ru_uz': 'Вы выбрали "ru ➡️ uz" язык\nВведите текст, который хотите перевести',
    'uz_ru': 'Siz "uz ➡️ ru" tilini tanladingiz\nKerakli matnni kiriting',
    'ru_en': 'Вы выбрали "ru ➡️ en" язык\nВведите текст, который хотите перевести',
    'en_ru': 'You chose "en ➡️ ru" language\nEnter the text you want to translate',
    'uz_tr': 'Siz "uz ➡️ tr" tilini tanladingiz\nKerakli matnni kiriting',
    'tr_uz': '"uz ➡️ tr" dilini seçtiniz\nGerekli metni girin',
    'ru_tr': 'Вы выбрали "ru ➡️ tr" язык\nВведите текст, который хотите перевести',
    'tr_ru': '"ru ➡️ tr" dilini seçtiniz\nGerekli metni girin',
    'en_tr': 'You chose "en ➡️ tr" language\nEnter the text you want to translate',
    'tr_en': '"en ➡️ tr" dilini seçtiniz\nGerekli metni girin',
    'uz_ar': 'Siz "uz ➡️ ar" tilini tanladingiz\nKerakli matnni kiriting',
    'ar_uz': 'Вы выбрали язык "uz ➡️ tr"\nВведите нужный текст',
    'ru_ar': 'Вы выбрали "ru ➡️ ar" язык\nВведите текст, который хотите перевести',
    'ar_ru': 'Вы выбрали язык "ar➡️ ru"\nВведите необходимый текст',
    'en_ar': 'You chose "en ➡️ ar" language\nEnter the text you want to translate',
    'ar_en': 'Вы выбрали язык "ar ➡️ en"\nВведите необходимый текст',
    'uz_kk': 'Siz "uz ➡️ kk" tilini tanladingiz\nKerakli matnni kiriting',
    'kk_uz': 'Сіз "kk ➡️ uz" тілін таңдадыңыз\nҚажетті мәтінді енгізіңіз',
    'ru_kk': 'Вы выбрали "ru ➡️ kk" язык\nВведите текст, который хотите перевести',
    'kk_ru': 'Сіз "kk ➡️ ru" тілін таңдадыңыз\nҚажетті мәтінді енгізіңіз',
    'en_kk': 'You chose "en ➡️ kk" language\nEnter the text you want to translate',
    'kk_en': 'Сіз "kk ➡️ en" тілін таңдадыңыз\nҚажетті мәтінді енгізіңіз',
    'uz_ko': 'Siz "uz ➡️ ko" tilini tanladingiz\nKerakli matnni kiriting',
    'ko_uz': '당신은 "ko ➡️ uz" 언어를 선택했습니다\n번역하려는 텍스트를 입력하십시오',
    'ru_ko': 'Вы выбрали "ru ➡️ ko" язык\nВведите текст, который хотите перевести',
    'ko_ru': '당신은 "ko ➡️ ru" 언어를 선택했습니다\n번역하려는 텍스트를 입력하십시오',
    'en_ko': 'You chose "en ➡️ ko" language\nEnter the text you want to translate',
    'ko_en': '당신은 "ko ➡️ en" 언어를 선택했습니다\n번역하려는 텍스트를 입력하십시오',
    'uz_ja': 'Siz "uz ➡️ ja" tilini tanladingiz\nKerakli matnni kiriting',
    'ja_uz': 'あなたは "ja ➡️ uz" 言語を選択しました\n翻訳したいテキストを入力してください',
    'ru_ja': 'Вы выбрали "ru ➡️ ja" язык\nВведите текст, который хотите перевести',
    'ja_ru': 'あなたは "ja ➡️ ru" 言語を選択しました\n翻訳したいテキストを入力してください',
    'en_ja': 'You chose "en ➡️ ja" language\nEnter the text you want to translate',
    'ja_en': 'あなたは "ja ➡️ en" 言語を選択しました\n翻訳したいテキストを入力してください',
    'uz_de': 'Siz "uz ➡️ de" tilini tanladingiz\nKerakli matnni kiriting',
    'de_uz': 'Sie haben die Sprache "de ➡️ uz" ausgewählt\nGeben Sie den zu übersetzenden Text ein',
    'ru_de': 'Вы выбрали "ru ➡️ de" язык\nВведите текст, который хотите перевести',
    'de_ru': 'Sie haben die Sprache "de ➡️ ru" ausgewählt\nGeben Sie den zu übersetzenden Text ein',
    'en_de': 'You chose "en ➡️ de" language\nEnter the text you want to translate',
    'de_en': 'Sie haben die Sprache "de ➡️ en" ausgewählt\nGeben Sie den zu übersetzenden Text ein',
}


language_mappings = {
    'uz_en': ('uz', 'en'),
    'en_uz': ('en', 'uz'),
    'ru_uz': ('ru', 'uz'),
    'uz_ru': ('uz', 'ru'),
    'ru_en': ('ru', 'en'),
    'en_ru': ('en', 'ru'),
    'uz_tr': ('uz', 'tr'),
    'tr_uz': ('tr', 'uz'),
    'ru_tr': ('ru', 'tr'),
    'tr_ru': ('tr', 'ru'),
    'en_tr': ('en', 'tr'),
    'tr_en': ('tr', 'en'),
    'uz_ar': ('uz', 'ar'),
    'ar_uz': ('ar', 'uz'),
    'ru_ar': ('ru', 'ar'),
    'ar_ru': ('ar', 'ru'),
    'en_ar': ('en', 'ar'),
    'ar_en': ('ar', 'en'),
    'uz_kk': ('uz', 'kk'),
    'kk_uz': ('kk', 'uz'),
    'ru_kk': ('ru', 'kk'),
    'kk_ru': ('kk', 'ru'),
    'en_kk': ('en', 'kk'),
    'kk_en': ('kk', 'en'),
    'uz_ko': ('uz', 'ko'),
    'ko_uz': ('ko', 'uz'),
    'ru_ko': ('ru', 'ko'),
    'ko_ru': ('ko', 'ru'),
    'en_ko': ('en', 'ko'),
    'ko_en': ('ko', 'en'),
    'uz_ja': ('uz', 'ja'),
    'ja_uz': ('ja', 'uz'),
    'ru_ja': ('ru', 'ja'),
    'ja_ru': ('ja', 'ru'),
    'en_ja': ('en', 'ja'),
    'ja_en': ('ja', 'en'),
    'uz_de': ('uz', 'de'),
    'de_uz': ('de', 'uz'),
    'ru_de': ('ru', 'de'),
    'de_ru': ('de', 'ru'),
    'en_de': ('en', 'de'),
    'de_en': ('de', 'en'),
}
