version: '3.9'

services:
  bot:
    build: .
    container_name: translation_bot
    restart: always
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
version: '3.3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ${BOT_NAME}
#    env_file:
#      - .env